### ISSUE TITLE
Details page tweaks

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#107]
On the details page, the parameterLabel and parameterValue elements (td classes) are too close to each other. Can we add some padding to the right of the label or left of the value to give them a little breathing room?  
Also, is there a reason the label "File Identifier" splits across two lines, while other two-word labels like "Contact Person" and "Date Modified" stay on one line? Is this just because the "abstract" always fills up the table and pushes the labels as far right as possible? (This is not a new problem, it shows up on the old pages too.)  Any way we can set a minimum width on the left cell so this doesn't occur?
The links "Details", "Review" and "Relationships" are also too close, can we space them out?

**Comment by Saisuma004** [comment]
There are fixed css applied for the whole grid in Schema code, as we cannot change the table structure (as the table generated by schema code). Added changes to the main css file and committed the code.

**Comment by torrin47** [comment]
Great, that really worked for the second two issues - placing a fixed width on the labels column and spacing out the  "Details", "Review" and "Relationships" links. But you're saying that there's no way to apply/force a css element just for the details page that adds padding to a certain class of table cells?
