### ISSUE TITLE
Add gallery functionality to new home page

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#12]
- [x] Ana would like two visible gallery sections on the home page - the first one would be titled "Featured Data Products" and the second one "Popular Datasets".  
- [x] Under Featured Data Products would be 3 tabs - "Climate Change", "Environmental Justice", and "Facility Data", and selecting a tab would show a corresponding set of thumbnails.  Popular datasets would not have a similar set of tabs.  
- [x] Each gallery would display 6 thumbnails across (most EDG metadata records do not have thumbnails today, we're working on that, there should be a default thumbnail image that displays when the metadata does not have a thumbnail). Some example galleries seem to allow horizontal scrolling (http://fema.maps.arcgis.com/home/index.html) maybe we can add this in in a later sprint.
- [x] At the bottom right of each gallery there should be a "see more" link that would link users to the main search results page with an appropriate search for the rest of the records corresponding to the featured or popular list. 
- [x] Each thumbnail should link to the details page for the corresponding metadata record (Template URL:  https://edg.epa.gov/metadata/catalog/search/resource/details.page?uuid={d8866557-05f6-4622-a873-f74ee726a6ee}) the metadata title would appear below the thumbnail, and the abstract/description would appear as a hovertip.

The idea is to use EDG's custom compilations to manage the galleries - the top 50 most popular datasets are already managed in a compilation, visible via API here:
https://edg.epa.gov/metadata/rest/find/document?f=json&childrenof={9007D9FF-E18F-9A91-564F-5C4FF3FAB904} if a record has a thumbnail, it seems to be included in the list of links - this search shows a couple of examples: https://edg.epa.gov/metadata/rest/find/document?searchText=usgs&start=1&max=25&f=json
Below is a clumsily marked-up mockup.  

![screenshot](https://cloud.githubusercontent.com/assets/2127036/16213603/aa9f9c36-371e-11e6-9b83-be627a37edc1.png)

**Comment by torrin47** [comment]
For reference - here are the links that Ana really liked.
https://www.nyclimatescience.org/highlights/data_products
https://databasin.org/galleries/

**Comment by Saisuma004** [comment]
Added document image.

**Comment by torrin47** [comment]
Need a different search to be performed for each featured section.  So a total of four separate queries to the EDG.  Popular items will be this one:
https://edg.epa.gov/metadata/rest/find/document?childrenof={9007D9FF-E18F-9A91-564F-5C4FF3FAB904}&start=1&max=6&f=json
key is that search params change for each and are tied to the corresponding div.  See more link should launch with matching search text (anything between ? and first &.  That's really the only piece that will vary between the tabbed sections.  Whether it's:
childrenof={9007D9FF-E18F-9A91-564F-5C4FF3FAB904}
or 
"?searchText=Climate"
that's the piece that's going to vary.

**Comment by torrin47** [comment]
Looks like "See More" links are still pointing to the old search strings.
