### ISSUE TITLE
Remove "Review" link from details page

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#120]
Ana loves the new look and feel and wants to move it to production as soon as we're ready. Her one point of feedback was on the details page - below the navigation bar and above the metadata title there are three links: Details, Review, and Relationships.  She would like to remove (or at least comment out/hide) the "Review" link because we don't use it and it creates confusion. 

Once we implement that and the small tweaks we discussed today (moving contact us and share up to the top, renaming the big green feedback button and some of the odd font sizes on the home page I think we'll finally go live!  Woohoo!

**Comment by Saisuma004** [comment]
That is great to hear. I have updated and checked in changes we have discussed except Share button. I did spent some time on Share button which has inbuilt code inside the css not working inside the form (banner.jsp), or outside the form. I will keep you posted on this.
