### ISSUE TITLE
Track usage of search terms

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#2]
The search terms from any search (web page, REST API, CSW, etc) should be captured and stored in a database table. The database table should contain two columns - one for the search term itself, and a second that contains the count of how many times that term was used in a search.  

Potential enhancements down the road:
- Would we ever want to track usage of search terms over time (like Google does to analyze spikes) or would that be overkill for a site like the EDG with so little traffic?
- Would be fantastic to add a page to the "Inventory" webapp that displays summary statistics for search terms in a nice user interface.

**Comment by Saisuma004** [comment]
Table that has to be created for saving search term:

Table name: GPT_SEARCH_TERM 

Columns:
  num_of_occurances (integer),
  sterm (text)

**Comment by torrin47** [comment]
Code was committed to saisuma fork, never merged with EDG_Metadata fork.  Submitted pull request https://github.com/Saisuma004/EDG_metadata/pull/2 to merge code, then can submit a second pull request to get the new search code into the main fork.

**Comment by Saisuma004** [comment]
I can see the Search term changes in EDG_Metadata fork.Files
GptRepository.java, ISearchSaveRepository.java.
There are some discrepancies that I have resolved with the file
SearchHarvestSitesController.java
and I have committed to EDG_Metadata.
Let me know if you do not see the changes.

On Thu, Jul 14, 2016 at 1:18 PM, Torrin Hultgren notifications@github.com
wrote:

> Code was committed to saisuma fork, never merged with EDG_Metadata fork.
> Submitted pull request Saisuma004#2
> https://github.com/Saisuma004/EDG_metadata/pull/2 to merge code, then
> can submit a second pull request to get the new search code into the main
> fork.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/Innovate-Inc/EDG_metadata/issues/2#issuecomment-232779899,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQVVNsjvK79yN1YGMyBpiFk9_5IdX340ks5qVpmhgaJpZM4ICkuw
> .

## 

Sumalatha Malothu
Innovate!, Inc.
Cell:  (318) 278-4228
http://www.innovateteam.com

**Comment by torrin47** [comment]
Hey, I resolved this one!  While looking for something else in the log files I noticed permission errors relating to the gpt_search_term table.  Turned out it was owned by postgres instead of gptlv10 - probably my error.  Changing the owner resolved the issue, wahoo!

**Comment by torrin47** [comment]
Ok, seems to be working fine on searches from home page but not search page... why not???
