### ISSUE TITLE
Use Kiki's Mockup to upgrade EDG Home Page

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#4]
Mockup page:

http://andyy.byethost7.com/edg_redesign

[edg_redesign.zip](https://github.com/Innovate-Inc/EDG_metadata/files/209403/edg_redesign.zip)

**Comment by torrin47** [comment]
A few punchlist items based on testing in staging...
- [ ] All traffic on EDG (and as of this March, all traffic to all EPA websites) must be over HTTPS.  It looks like the template Kiki provided us loaded a number of standard EPA libraries over HTTP - she must have developed the mockup before the agency HTTPS transition.  Can we switch these references to be explicitly HTTPS?  Worth getting into a habit of always testing in HTTPS, even in development.
- [x] On the new home page, the "Share Your Feedback" button isn't appearing as a big green button (the look was specifically requested by Ana) because the .bigGreen css class isn't in catalog\skins\themes\blue\css\main.css - can we add it?  
- [x] The two icons to the right of the search box aren't wired up to anything at the moment.  Can we link the browse button to the browse page (https://edg-staging.epa.gov/metadata/catalog/search/browse/browse.page) and the metrics button to this relative URL?  https://edg-staging.epa.gov/metrics/

I'm sure when Ana sees the page we're going to have a much longer list of things to work on, but these ought to be some quick fixes.  Thanks!

**Comment by torrin47** [comment]
Still seeing these two links appearing in the console as unsecured:
http://fonts.googleapis.com/css?family=Lato:100,300,400,700
http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js

Let's fill in EPA's slogan above the search box:
"Find data easily. Connecting EPA's Environmental Resources."

I feel like there's a whole lot of blue space at the top of the page. I experimented in Chrome and was able to reduce the space by giving the secondary nav a height of 0 - this didn't seem to have a downside:
<nav class="nav simple-nav simple-secondary-nav" role="navigation" style="height: 0px">

Also, now that I've resolved the login issues in staging, I'm able to see what the page looks like after a successful login. We're frustratingly limited in our ability to grant you access to the EDG site to see this for yourself.  But here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/2127036/15082571/6ee530f8-1396-11e6-8eed-b5e78df50a02.png)
The top row adds a "Welcome username" and a Logout link and Two additional buttons appear on the navigation bar - Administration and Compilations.  In the screenshot there's also a link to the EDG Inventory - but in the new page we're linking there from the "Metrics" icon, so for now I think we can omit this. I'm not sure what Ana will think about making that metrics link visible without a login!

**Comment by Saisuma004** [comment]
Hi Torrin,

Checked in above changes. The above screenshot looks different compared to
what we have seen on local. Have you added extra links and tabs?

On Fri, May 6, 2016 at 11:29 AM, Torrin Hultgren notifications@github.com
wrote:

> Still seeing these two links appearing in the console as unsecured:
> http://fonts.googleapis.com/css?family=Lato:100,300,400,700
> http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js
> 
> Let's fill in EPA's slogan above the search box:
> "Find data easily. Connecting EPA's Environmental Resources."
> 
> I feel like there's a whole lot of blue space at the top of the page. I
> experimented in Chrome and was able to reduce the space by giving the
> secondary nav a height of 0 - this didn't seem to have a downside:
> 
> Also, now that I've resolved the login issues in staging, I'm able to see
> what the page looks like after a successful login. We're frustratingly
> limited in our ability to grant you access to the EDG site to see this for
> yourself. But here's a screenshot:
> [image: image]
> https://cloud.githubusercontent.com/assets/2127036/15082571/6ee530f8-1396-11e6-8eed-b5e78df50a02.png
> The top row adds a "Welcome username" and a Logout link and Two additional
> buttons appear on the navigation bar - Administration and Compilations. In
> the screenshot there's also a link to the EDG Inventory - but in the new
> page we're linking there from the "Metrics" icon, so for now I think we can
> omit this. I'm not sure what Ana will think about making that metrics link
> visible without a login!
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/Innovate-Inc/EDG_metadata/issues/4#issuecomment-217522592

## 

Sumalatha Malothu
Innovate!, Inc.
Office: (703) 461-2263
Cell:  (318) 278-4228
http://www.innovateteam.com

**Comment by torrin47** [comment]
Thanks much, got the updates into staging.  Providing alternate links after a successful login is part of the standard Esri off-the-shelf functionality.  We have customized them slightly, but the base code should be there.  As an example, here's the out-of-the-box look and feel on Esri's sandbox server:
http://gptogc.esri.com/geoportal/catalog/main/home.page
![image](https://cloud.githubusercontent.com/assets/2127036/15123333/4bb9df9a-15f1-11e6-8202-7854a6aee976.png)
and here's what it looks like after a login.
![image](https://cloud.githubusercontent.com/assets/2127036/15123319/40191476-15f1-11e6-8d5a-c3cb93095044.png)
we don't allow external users to register, and we've added a "compilation" module, but most of the rest of the links are analogous and should be in your copy of the staging code.  Is the search issue affecting your ability to log in locally?

**Comment by Saisuma004** [comment]
Oh I see what you were seeing, I see the samething.

On Mon, May 9, 2016 at 2:22 PM, Torrin Hultgren notifications@github.com
wrote:

> Thanks much, got the updates into staging. Providing alternate links after
> a successful login is part of the standard Esri off-the-shelf
> functionality. We have customized them slightly, but the base code should
> be there. As an example, here's the out-of-the-box look and feel on Esri's
> sandbox server:
> [image: image]
> https://cloud.githubusercontent.com/assets/2127036/15123333/4bb9df9a-15f1-11e6-8202-7854a6aee976.png
> and here's what it looks like after a login.
> [image: image]
> https://cloud.githubusercontent.com/assets/2127036/15123319/40191476-15f1-11e6-8d5a-c3cb93095044.png
> we don't allow external users to register, and we've added a "compilation"
> module, but most of the rest of the links are analogous and should be in
> your copy of the staging code. Is the search issue affecting your ability
> to log in locally?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/Innovate-Inc/EDG_metadata/issues/4#issuecomment-217946478

## 

Sumalatha Malothu
Innovate!, Inc.
Office: (703) 461-2263
Cell:  (318) 278-4228
http://www.innovateteam.com
