### ISSUE TITLE
Add EPA Regions section to Home page.

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#53]
Envision this would be a row of 10 tabs that look similar to the "Featured Data Products" (6 thumbnails and a "See More" link to a full search page) but would be located under Popular Datasets.  
The search syntax for each region is:
https://edg.epa.gov/metadata/rest/find/document?owner=Region%201&f=json
https://edg.epa.gov/metadata/rest/find/document?owner=Region%202&f=json
etc.

There should also be a "Find my region" link that pops up a modal with an image map that shows the "US Map Split into regions" and allows a user to click on a region that closes the modal and selects the corresponding tab. All details for implementing this image map are at this link:
https://www.epa.gov/webguide/how-build-standard-us-national-maps

**Comment by torrin47** [comment]
## How to Build Standard U.S. National Maps
This page provides standard maps for use on Where You Live pages. To use a map:

1. Download the HTML code for the appropriate map. Modify the link destinations in both the state selection table and the image map. Use the code provided because it includes required accessibility features.
2. Use the correct map graphic file: if you have information for all areas of a map, don't download the map. Instead, use the image map code provided without modifying the <img> tag. It uses an absolute URL so that everyone uses the same map files, just as we all use the same EPA seal file.
3. Use responsive image map plugin: Because EPA's One EPA Web template is responsive, if you use image maps, you must also use the Responsive Image Maps jQuery Plugin, which allows image maps to be used in a responsive design by recalculating the area coordinates to match the actual image size on load and window.resize.

**US map split into EPA regions**
Features:

- 450 pixels wide x 340 pixels high
- One image map area per EPA Region, so blind people don't hear a given Region read twice (e.g., Alaska and R10 are in the same image map region, despite not being next to each other); alt text is region name followed by the region's full state names in alphabetical order
- The image map areas are in region number order, so they are heard in proper order through a screen reader
- The PSD file has one layer per type of information; each Region has its own group within each layer:
- image map areas
- state names and name boxes (e.g., NJ, DE, etc.)
- state shapes and boxes (e.g., AK, HI, etc.)
- regional markers
- grayed-out areas (to mark regions for which there is no information)
- Use the PSD or PNG files only to create custom maps as needed (e.g., with grayed-out areas) in PNG format. Do not use PSD files on the Web site itself.
- The HTML code includes all relevant links:
- image map code, including alt text; set the href attribute for each image map area to the correct destination using relative URLs
- a form to let people choose their state; set the value attribute of each selection option to the correct destination using absolute URLs
- The Javascript code includes the necessary javascript for the dropdown list of states to function properly.  This should be pasted into the "Page Javascript" field in the Drupal WebCMS.

Download Files
Use the PSD file only to create custom maps (for example, with grayed-out areas) and save them in PNG format. Don't use PSD files on the Web site itself.
US split into regions: 
[us-regions.txt](https://github.com/Innovate-Inc/EDG_metadata/files/694127/us-regions.txt)
[regions-javascript.txt](https://github.com/Innovate-Inc/EDG_metadata/files/694128/regions-javascript.txt)
[us-regions.zip](https://github.com/Innovate-Inc/EDG_metadata/files/694129/us-regions.zip)
![us-regions](https://cloud.githubusercontent.com/assets/2127036/21775592/c1041cbe-d664-11e6-9c78-d822d4fab840.png)

Don't turn on the HQ "seal" layer unless you have a specific and clear need to link to HQ in general.

**Comment by torrin47** [comment]
Here is the crosswalk for the different regions and their lucene search index shown here:
https://edg.epa.gov/metadata/rest/index/stats/fields?field=sys.owner
If there's any way we can implement this crosswalk on the search page, it would be fantastic.
Region 01 = sys.owner:4
Region 02 = sys.owner:9
Region 03 = sys.owner:22
Region 04 = sys.owner:27
Region 05 = sys.owner:13
Region 06 = sys.owner:26
Region 07 = sys.owner:10
Region 08 = sys.owner:15
Region 09 = sys.owner:11
Region 10 = sys.owner:??  No records owned, don't believe index is assigned without at least one record.

**Comment by torrin47** [comment]
Text above map should say:  "Please click on the map to select a region"

**Comment by torrin47** [comment]
Awesome work.  A few notes.  

- [x] The text in the "Find my region" button seems to be flush with the bottom instead of centered, as you would ordinarily expect it to be in a button.  Are we able to center this? 
![image](https://cloud.githubusercontent.com/assets/2127036/22039684/3f91f370-dcce-11e6-9b4f-9d266454fec8.png)
- [x] Can we load the us-regions.png over HTTPS? https://www.epa.gov/sites/production/files/2013-06/us-regions.png
- [x] The search text that appears after clicking "see more" seems to work perfectly, but the text isn't quite what I was expecting, but because it's working so well, maybe this is an easy fix?  I was anticipating that no matter what happens with the mappings behind the scenes what would appear in the search box would be:
owner=Region 01
owner=Region 02 
etc., so that it would be consistent with the REST API syntax:
https://edg.epa.gov/metadata/rest/find/document?owner=Region%201
However, I know that part of the problem is that in the REST API, what we enter in the search field is actually a different parameter - searchText - so we might not be able to use the equals sign (though it seems to be working for you!) I was expecting that it might end up something like this:
owner:"Region 01"
owner:"Region 02"
https://edg.epa.gov/metadata/rest/find/document?searchText=owner:%22Region%2001%22
Both options look ok to the end user, which would be the most practical to implement?

**Comment by Saisuma004** [comment]
checked in changes

**Comment by torrin47** [comment]
Scribbled thoughts... 

![image](https://cloud.githubusercontent.com/assets/2127036/22214641/5ab06e42-e166-11e6-89ba-c5a66fda95ba.png)

**Comment by torrin47** [comment]
So, a summary of what we discussed today...

- [ ] Instead of entering owner=Region 0X into the search text, it would be more intuitive to leave the search box empty, and add checkboxes to the page that would filter the search results based on the regional owners.  (In effect, this is creating the first "faceted search" functionality on the search page).
- [ ] There would also be an "All Regions" checkbox that would be checked by default (all of the individual regions would be unchecked by default). If a user checks a box by a region, the "all regions" checkbox would toggle off.  
- [ ] A user may check multiple regions and the results would be additive. 
- [ ] The search results would not be updated until a user clicks the "Search" button. 
- [ ] If a user clicks the "See More" button for one of the regional tabs on the home page, the search page would appear with that region's box checked and the search results showing.

**Comment by torrin47** [comment]
Moving all of this to a new issue, so we can consider this one closed.
