### ISSUE TITLE
Edits to Discussion Forum Link

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#6]
In the staging version of the site, on the Details page for every metadata record there is currently a link that says "Discussion Forum".  Ana would like this link to be moved to the right side of the screen to make it stand out, and the text be changed to "Share Your Feedback".   There is already a big green "Share Your Feedback" link shown at the top of every page. Ana would like this big green button to be hidden on Details pages, but to remain on any other page.

**Comment by torrin47** [comment]
Looking great, two punchlist items.
- [x] The big green "Share Your Feedback" button still appears in Internet Explorer
- [x] The template link needs to change slightly to https://developer.epa.gov/new-forum-topic/topic?uuid=%7BC0627CEF-D34E-4C14-813F-85D68DEB6BE3%7D

**Comment by Saisuma004** [comment]
Checked in changes to EDG_branch.

**Comment by torrin47** [comment]
Yay!
