### ISSUE TITLE
Get EDG staging database working in local development environment

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#61]
This was a big challenge but it's finally working, hooray!

**Comment by Saisuma004** [comment]
Steps involved in getting EDG Staging database in local environment.
Commands used to restore, grant privileges to the schema, reset user passowrd and finally login with the role.
**STEP 1**: (Restore database) 
pg_restore -i -h localhost -p 5432 -U postgres -d staging -v  "C:\Users\Innovate\Downloads\ProductionExport20160912\ProductionExport20160912.backup"
STEP 2 : GRANT ALL PRIVILEGES ON SCHEMA gptlv10 TO gptlv10;
STEP 3 : ALTER USER gptlv10 WITH PASSWORD 'gptlv10';
STEP 4 : ALTER ROLE gptlv10 WITH LOGIN;
