### ISSUE TITLE
Implement temporalField fix

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EDG_metadata#67]
We logged this issue with Esri:
https://github.com/Esri/geoportal-server/issues/254
and they implemented this fix:
https://github.com/Esri/geoportal-server/commit/988628f7194fe322639a759321cac3de8fed0af7
I'm not completely satisfied with the fix, but it's acceptable as a workaround.  Could we grab this file, compile it, and implement it in our catalog?

**Comment by torrin47** [comment]
Actually, I wonder whether we could implement my preferred solution - instead of setting the date to "null", set it to "now", that is, the time at which the dcat output is being generated.

**Comment by Saisuma004** [comment]
Sure, I will make that change and test it on local.

**Comment by torrin47** [comment]
Esri liked our fix on this issue and requested that we submit a pull request back to their source repository with the updated code, and they'll incorporate it as a configurable choice.  Thanks!

**Comment by torrin47** [comment]
All good, thanks!
